### ISSUE TITLE
Not working on SSR

### ISSUE THREAD

**Issue by homerjam** [ymmooot/nuxt-jsonld#1085]
**Describe the bug**
Works fine in dev mode but the application/ld+json script tag is missing in prod

Deployed:
https://csb-kzqp5j.vercel.app/

**Your Nuxt version**
`2.16.0`

**Your nuxt-jsonld version**
`1.5.3`

**To Reproduce**
https://codesandbox.io/s/serverless-shadow-kzqp5j?file=/pages/index.vue

**Comment by ymmooot** [comment]
Hi @homerjam 
You are using `@nuxt/bridge` and it handles head differently.
I will fix it.

**Comment by ymmooot** [comment]
woops, it does not still working.

**Comment by ymmooot** [comment]
@homerjam 
I have just released v1.5.6.
Please try it and tell me if something wrong.

**Comment by codeofsumit** [comment]
Still not working in SSR.
Works fine if I add the structuredData via script tag directly in `head()` instead

**Comment by ymmooot** [comment]
This issue has already been fixed.
@codeofsumit please create new issue with your version info 🙏
