### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by khrome83** [ymmooot/nuxt-jsonld#16]
This does not appear to work... really excited to use it though. 

I added the plugin, copy and pasted the code (minus the configuration)
Added the `jsonld()` to my index.vue file within pages. 

Nothing happened. Added to default.vue within layouts also, got nothing. 

Looked at the code and reviewed the /examples folder. I saw there was a plugin line within `nuxt.config.js` which was missing from the docs (is it needed?). Added that, nothing.

I changed the extension from `.js` to `.ts` as I use a typescript project. Nothing.

I assume this is suppose to add this to the head of the site. 

I have viewed the source on the output, both using `nuxt` and `nuxt generate` with all the different combinations and attempts. Nothing.

I can search the souirce, and I do see a JavaScript file appears to show that i was compiled somewhere along the way. 

```
(window.webpackJsonp = window.webpackJsonp || []).push([[2], {
    295: function(e, t, n) {
        "use strict";
        n.r(t);
        n(41);
        var c = n(23),
            o = n(40),
            r = n(26),
            l = n(24),
            f = n(25),
            h = n(5),
            d = n(2),
            w = function(e, t, n, desc) {
                var c,
                    o = arguments.length,
                    r = o < 3 ? t : null === desc ? desc = Object.getOwnPropertyDescriptor(t, n) : desc;
                if ("object" === ("undefined" == typeof Reflect ? "undefined" : Object(h.a)(Reflect)) && "function" == typeof Reflect.decorate)
                    r = Reflect.decorate(e, t, n, desc);
                else
                    for (var i = e.length - 1; i >= 0; i--)
                        (c = e[i]) && (r = (o < 3 ? c(r) : o > 3 ? c(t, n, r) : c(t, n)) || r);
                return o > 3 && r && Object.defineProperty(t, n, r), r
            },
            j = function(e) {
                function t() {
                    return Object(c.a)(this, t), Object(r.a)(this, Object(l.a)(t).apply(this, arguments))
                }
                return Object(f.a)(t, e), Object(o.a)(t, [{
                    key: "jsonld",
                    value: function() {
                        return {
                            "@context": "https://schema.org",
                            "@type": "Organization",
                            url: "https://www.example.com",
                            logo: "https://www.example.com/logo.png",
                            contactPoint: [{
                                "@type": "ContactPoint",
                                telephone: "+1-401-555-1212",
                                contactType: "customer service"
                            }]
                        }
                    }
                }]), t
            }(d.Vue),
            O = j = w([Object(d.Component)({})], j),
            y = n(12),
            component = Object(y.a)(O, function() {
                this.$createElement;
                this._self._c;
                return this._m(0)
            }, [function() {
                var e = this.$createElement,
                    t = this._self._c || e;
                return t("section", [t("h1", {
                    staticClass: "header"
                }, [this._v("Content")])])
            }], !1, null, "e1b7e7d8", null);
        t.default = component.exports
    }
}]);
```

### Plugin File
```
import Vue from "vue";
import NuxtJsonld from "nuxt-jsonld";

Vue.use(NuxtJsonld);

```

**Comment by chuckcharles** [comment]
Same here. Seems simple enough to implement. I've implemented in component (~/components/) which is included in page component (~/pages/) yet yields no result.

**Comment by ymmooot** [comment]
Thank you for your reporting.
I will fix it. Please wait for it 🙏

**Comment by ymmooot** [comment]
You need to add a setting about plugin to nuxt.config.js like as you say.

```js
{
  plugins: ['~/plugins/jsonld.js'], // or '@/plugins/jsonld.js'
}
```

I did the commands below and it worked right.

```bash
$ vue init nuxt-community/starter-template sample
$ cd sample
$ npm install nuxt-jsonld
$ npm install
$ vim nuxt.config.js // add plugin setting
$ vim pages/index.vue // add jsonld() method
$ npm run dev
```

Could you give me some reproducing repository?
(with something like [CodeSandbox](https://codesandbox.io/) tool)

**Comment by khrome83** [comment]
@ymmooot - unfortantly, it's a private repo. 

I did try with the plugin already. I retried using the `.js` and `.ts` extensions with no change. There are no errors, there is just nothing within the head of the document...

**Comment by ymmooot** [comment]
It is okay that the repo is private.
Could you make new environment which is reproducing the bug?
You can use [CodeSandbox](https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/tree/master/?autoresize=1&hidenavigation=1&view=preview) or push to a public repository.

**Comment by khrome83** [comment]
@ymmooot - it would take a lot to reproduce my configuration. There is no telling what is wrong without any errors. 

I use typescript with my build as well, so i don't know if that is causing a problem. 

Is there a way I can debug this to assist you?
Does this work with `nuxt dev` and `nuxt generate`, have you validated that?

**Comment by ymmooot** [comment]
@khrome83 

> it would take a lot to reproduce my configuration

Oh, okay. Thanks anyway. 
It should work right with `nuxt dev` and `nuxt generate`.
Also with `@nuxt/typescript`.

Could you confirm that it is installed correctly?
You can check it by writing a `console.log` to `install` method in `/node_modules/nuxt-jsonld/index.js` L59.

**Comment by ymmooot** [comment]
@khrome83 

I made a reproducing environment with typescript!!
I will fix this problem as soon as possible.

Thank you and please wait for it !!

**Comment by khrome83** [comment]
Ohh @ymmooot, thank you so much. Sorry I am still new to Nuxt and was not sure I could get another enviroment to work. I had so much trouble getting typescript to work the first time. =)

**Comment by ymmooot** [comment]
@khrome83 
I published v1.2.0 that supports TypeScript.
Please use new version and tell me anything if you have any questions.

**Comment by khrome83** [comment]
It seems something is still off with version 1.2.0

```
     7 | <script lang="ts">
     8 | import { Component, Vue } from "nuxt-property-decorator";
  >  9 | import { Jsonld } from "nuxt-jsonld";
       |          ^
    10 | 
    11 | @Jsonld
    12 | @Component({})
```

<img width="810" alt="Screen Shot 2019-05-31 at 10 53 17 AM" src="https://user-images.githubusercontent.com/1844739/58718076-566da180-8392-11e9-816e-ccd9eb0a73f2.png">

It appears the new version is missing a export.

**Comment by ymmooot** [comment]
Sorry for that, the issue is #18.
It is almost done, please wait for the release 🙏

**Comment by khrome83** [comment]
No problem. Thank you for the quick turn around and response. I saw the PR right after I posted this response. The second you get it up, I can test.

**Comment by ymmooot** [comment]
Thank you so much.
I have just released `v1.3.0`.
Could you try with this?

**Comment by khrome83** [comment]
Seeing the same issue after upgrading. Restarting my IDE and clearing NPM cache to be safe. One second.

**Comment by khrome83** [comment]
@ymmooot - still happening. Should there be a export statement here with Jsonld. Veutur seems to think so. I am still new to TS myself.

```
import Vue, { ComponentOptions } from 'vue'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    jsonld?: () => object;
  }
}

declare module 'vue/types/vue' {
  interface Vue {
    _uid: number
  }
}
```

**Comment by ymmooot** [comment]
Oh...
Sorry, some config is missing 🙇

**Comment by ymmooot** [comment]
@khrome83 please try with `v1.3.1`.

**Comment by khrome83** [comment]
@ymmooot  - Now a different problem.

```
11:50:45 ℹ Type checking in progress...

friendly-errors 11:50:45  ERROR  Failed to compile with 1 errors

friendly-errors 11:50:45 This relative module was not found:
friendly-errors 11:50:45 
friendly-errors 11:50:45 * ./declaration.d in ./node_modules/nuxt-jsonld/lib/index.js
```

<img width="1085" alt="Screen Shot 2019-05-31 at 11 51 02 AM" src="https://user-images.githubusercontent.com/1844739/58721377-7d2fd600-839a-11e9-8b47-93d73c6c7848.png">

**Comment by ymmooot** [comment]
@khrome83 Finally fixed on `v1.3.2`! Check it out 🚀

**Comment by khrome83** [comment]
@ymmooot - ok this is for sure working, I can see it, but there are some exceptions. First, think you so much for addressing it. 

Food for thought - It does not appear to be generated on the server with `nuxt generate`

I do use `spa` mode with Nuxt on `nuxt generate` so after the JS is downloaded, it does register the script. But viewing the source of the file from the server (right click > view source) you can see it is not present.

I am not 100% sure, but this may damage Google and other browsers abilties to craw the content. Is there a way to ensure this renders with the nuxt server render, @ymmooot?
